# Generated by Django 4.0.1 on 2022-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
